<#
    Script para criar issues via GitHub REST API e adicionar ao Project #2 (user-level).
    NÃO requer gh CLI - usa API REST diretamente.
    
    Requer: Personal Access Token do GitHub com permissões de repo e project.
    
    Uso:
    $env:GITHUB_TOKEN="ghp_..."
    pwsh ./scripts/create_issues_api.ps1 -ProjectNumber 2 -Owner fabioaap [-DryRun] [-CreateLabels]
    
    Ou interativo (pedirá o token):
    pwsh ./scripts/create_issues_api.ps1 -ProjectNumber 2 -Owner fabioaap
#>

param(
    [int]$ProjectNumber = 2,
    [string]$Owner = "fabioaap",
    [switch]$DryRun,
    [switch]$CreateLabels
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$issuesFile = Join-Path $scriptDir "issues.json"

if (-not (Test-Path $issuesFile)) {
    Write-Error "Arquivo de issues não encontrado: $issuesFile"
    exit 1
}

# Get GitHub token
$token = $env:GITHUB_TOKEN
if (-not $token) {
    Write-Host "GitHub Personal Access Token não encontrado em GITHUB_TOKEN." -ForegroundColor Yellow
    Write-Host "Para criar um token: https://github.com/settings/tokens/new" -ForegroundColor Cyan
    Write-Host "Permissões necessárias: repo, project" -ForegroundColor Cyan
    $token = Read-Host -Prompt "Cole seu GitHub token aqui" -AsSecureString
    $token = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($token))
}

$headers = @{
    "Authorization"        = "Bearer $token"
    "Accept"               = "application/vnd.github+json"
    "X-GitHub-Api-Version" = "2022-11-28"
}

# Detect repo from git remote
$remoteUrl = git remote get-url origin 2>$null
if (-not $remoteUrl) {
    Write-Error "Não foi possível obter remote origin do git"
    exit 1
}

if ($remoteUrl -match "github\.com[:/](.+)/(.+?)(\.git)?$") {
    $repoOwner = $matches[1]
    $repoName = $matches[2]
}
else {
    Write-Error "Não foi possível parsear remote origin: $remoteUrl"
    exit 1
}

Write-Host "Repositório detectado: $repoOwner/$repoName" -ForegroundColor Cyan
Write-Host "Project: #$ProjectNumber (owner: $Owner)" -ForegroundColor Cyan

$issues = Get-Content $issuesFile -Raw | ConvertFrom-Json

function Create-LabelIfMissing([string]$name, [string]$color) {
    if ($DryRun) {
        Write-Host "[dry-run] Criaria label: $name" -ForegroundColor Yellow
        return
    }
    
    $labelUrl = "https://api.github.com/repos/$repoOwner/$repoName/labels"
    try {
        $existingLabels = Invoke-RestMethod -Uri $labelUrl -Headers $headers -Method Get
        $exists = $existingLabels | Where-Object { $_.name -eq $name }
        
        if (-not $exists) {
            $labelBody = @{
                name        = $name
                color       = $color
                description = "Generated by scripts"
            } | ConvertTo-Json
            
            Invoke-RestMethod -Uri $labelUrl -Headers $headers -Method Post -Body $labelBody -ContentType "application/json" | Out-Null
            Write-Host "  Label criada: $name" -ForegroundColor Green
        }
    }
    catch {
        Write-Host "  Erro ao criar label $name : $_" -ForegroundColor Red
    }
}

if ($CreateLabels) {
    Write-Host "`nCriando labels no repositório..." -ForegroundColor Cyan
    $labelsToCreate = @(
        @{name = 'todo'; color = 'f9d0c4' },
        @{name = 'in-progress'; color = 'fef08a' },
        @{name = 'done'; color = 'b6f5b8' },
        @{name = 'tests'; color = 'f6ad55' },
        @{name = 'e2e'; color = 'a78bfa' },
        @{name = 'ci'; color = '60a5fa' },
        @{name = 'infra'; color = 'c084fc' },
        @{name = 'feature'; color = '34d399' },
        @{name = 'backend'; color = '38bdf8' },
        @{name = 'ux'; color = 'fb7185' },
        @{name = 'bug'; color = 'f87171' },
        @{name = 'perf'; color = 'fb923c' },
        @{name = 'future'; color = 'd1d5db' }
    )
    foreach ($label in $labelsToCreate) {
        Create-LabelIfMissing $label.name $label.color
    }
}

$createdIssues = @()

Write-Host "`nCriando issues..." -ForegroundColor Cyan

foreach ($issue in $issues) {
    $title = $issue.title
    $body = $issue.body
    $labels = $issue.labels
    $assignees = $issue.assignees

    if ($DryRun) {
        Write-Host "[dry-run] Criaria issue: $title" -ForegroundColor Yellow
        Write-Host "  Labels: $($labels -join ', ')" -ForegroundColor Gray
        Write-Host "  Assignees: $($assignees -join ', ')" -ForegroundColor Gray
        continue
    }

    Write-Host "  Criando: $title" -ForegroundColor Cyan
    
    $issueBody = @{
        title     = $title
        body      = $body
        labels    = @($labels)
        assignees = @($assignees)
    } | ConvertTo-Json -Depth 10
    
    try {
        $issueUrl = "https://api.github.com/repos/$repoOwner/$repoName/issues"
        $response = Invoke-RestMethod -Uri $issueUrl -Headers $headers -Method Post -Body $issueBody -ContentType "application/json"
        
        $issueNumber = $response.number
        $issueHtmlUrl = $response.html_url
        
        Write-Host "    ✅ Issue #$issueNumber criada: $issueHtmlUrl" -ForegroundColor Green
        
        $createdIssues += @{
            number = $issueNumber
            url    = $issueHtmlUrl
            nodeId = $response.node_id
        }
    }
    catch {
        Write-Host "    ❌ Erro ao criar issue: $_" -ForegroundColor Red
    }
}

if ($DryRun) {
    Write-Host "`n[dry-run] Terminado. Nenhuma issue foi criada." -ForegroundColor Yellow
    exit 0
}

if ($createdIssues.Count -eq 0) {
    Write-Host "`n❌ Nenhuma issue foi criada." -ForegroundColor Yellow
    exit 0
}

Write-Host "`nAdicionando issues ao Project #$ProjectNumber..." -ForegroundColor Cyan

# Get Project ID using GraphQL
$graphqlUrl = "https://api.github.com/graphql"
$projectQuery = @"
{
  user(login: "$Owner") {
    projectV2(number: $ProjectNumber) {
      id
    }
  }
}
"@

$projectQueryBody = @{
    query = $projectQuery
} | ConvertTo-Json

try {
    $projectResponse = Invoke-RestMethod -Uri $graphqlUrl -Headers $headers -Method Post -Body $projectQueryBody -ContentType "application/json"
    $projectId = $projectResponse.data.user.projectV2.id
    
    if (-not $projectId) {
        Write-Host "❌ Não foi possível obter ID do Project #$ProjectNumber" -ForegroundColor Red
        Write-Host "Verifique se o project existe e se o token tem permissões corretas." -ForegroundColor Yellow
        exit 1
    }
    
    Write-Host "  Project ID: $projectId" -ForegroundColor Gray
    
    foreach ($issue in $createdIssues) {
        Write-Host "  Adicionando issue #$($issue.number) ao project..." -ForegroundColor Cyan
        
        $addMutation = @"
mutation {
  addProjectV2ItemById(input: {projectId: "$projectId", contentId: "$($issue.nodeId)"}) {
    item {
      id
    }
  }
}
"@
        
        $addMutationBody = @{
            query = $addMutation
        } | ConvertTo-Json
        
        try {
            $addResponse = Invoke-RestMethod -Uri $graphqlUrl -Headers $headers -Method Post -Body $addMutationBody -ContentType "application/json"
            
            if ($addResponse.data.addProjectV2ItemById.item.id) {
                Write-Host "    ✅ Issue #$($issue.number) adicionada ao project" -ForegroundColor Green
            }
            else {
                Write-Host "    ⚠️  Issue #$($issue.number) pode já estar no project ou houve erro" -ForegroundColor Yellow
            }
        }
        catch {
            Write-Host "    ❌ Erro ao adicionar issue #$($issue.number): $_" -ForegroundColor Red
        }
    }
    
}
catch {
    Write-Host "❌ Erro ao buscar Project ID: $_" -ForegroundColor Red
    Write-Host "Verifique se o project #$ProjectNumber existe para o usuário $Owner" -ForegroundColor Yellow
    exit 1
}

Write-Host "`n✅ Concluído!" -ForegroundColor Green
Write-Host "Issues criadas: $($createdIssues.Count)" -ForegroundColor Cyan
Write-Host "Visualize o project em: https://github.com/users/$Owner/projects/$ProjectNumber" -ForegroundColor Cyan
