<#
    Script para criar issues a partir de issues.json e adicionar a um Project user-level existente.
    Requer: gh CLI autenticado (gh auth login)
    
    Uso:
    pwsh ./scripts/create_issues_and_add_to_project.ps1 -ProjectNumber 2 -Owner fabioaap [-DryRun] [-CreateLabels]
#>

param(
    [int]$ProjectNumber = 2,
    [string]$Owner = "fabioaap",
    [switch]$DryRun,
    [switch]$CreateLabels
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$issuesFile = Join-Path $scriptDir "issues.json"

if (-not (Test-Path $issuesFile)) {
    Write-Error "Arquivo de issues não encontrado: $issuesFile"
    exit 1
}

try {
    $null = Get-Command gh -ErrorAction Stop
}
catch {
    Write-Host "GitHub CLI (gh) não encontrado. Instale e autentique: https://cli.github.com/" -ForegroundColor Yellow
    exit 1
}

$issues = Get-Content $issuesFile -Raw | ConvertFrom-Json

function Create-LabelIfMissing([string]$name, [string]$color, [string]$repo) {
    $existing = gh label list --repo $repo --json name -q ".[] | select(.name == `"$name`")" 2>$null
    if (-not $existing) {
        if ($DryRun) {
            Write-Host "[dry-run] gh label create --repo $repo --name '$name' --color '$color'"
        }
        else {
            gh label create --repo $repo --name "$name" --color "$color" --description "Generated by scripts" 2>&1 | Out-Null
            Write-Host "Label created: $name" -ForegroundColor Green
        }
    }
}

# Detect repo from git remote
$remoteUrl = git remote get-url origin 2>$null
if (-not $remoteUrl) {
    Write-Error "Não foi possível obter remote origin do git"
    exit 1
}

if ($remoteUrl -match "github\.com[:/](.+)/(.+?)(\.git)?$") {
    $repoOwner = $matches[1]
    $repoName = $matches[2]
    $repo = "$repoOwner/$repoName"
}
else {
    Write-Error "Não foi possível parsear remote origin: $remoteUrl"
    exit 1
}

Write-Host "Repositório detectado: $repo" -ForegroundColor Cyan

if ($CreateLabels) {
    Write-Host "Criando labels básicos no repositório $repo..." -ForegroundColor Cyan
    $labelsToCreate = @(
        @{name = 'todo'; color = 'f9d0c4' },
        @{name = 'in-progress'; color = 'fef08a' },
        @{name = 'done'; color = 'b6f5b8' },
        @{name = 'tests'; color = 'f6ad55' },
        @{name = 'e2e'; color = 'a78bfa' },
        @{name = 'ci'; color = '60a5fa' },
        @{name = 'infra'; color = 'c084fc' },
        @{name = 'feature'; color = '34d399' },
        @{name = 'backend'; color = '38bdf8' },
        @{name = 'ux'; color = 'fb7185' },
        @{name = 'bug'; color = 'f87171' },
        @{name = 'perf'; color = 'fb923c' },
        @{name = 'future'; color = 'd1d5db' }
    )
    foreach ($label in $labelsToCreate) {
        Create-LabelIfMissing $label.name $label.color $repo
    }
}

$createdIssueNumbers = @()

foreach ($issue in $issues) {
    $title = $issue.title
    $body = $issue.body
    $labels = $issue.labels
    $assignees = $issue.assignees

    if ($DryRun) {
        Write-Host "[dry-run] Criaria issue: $title" -ForegroundColor Yellow
        Write-Host "  Labels: $($labels -join ', ')" -ForegroundColor Gray
        Write-Host "  Assignees: $($assignees -join ', ')" -ForegroundColor Gray
        continue
    }

    Write-Host "Criando issue: $title" -ForegroundColor Cyan
    
    $tempFile = [System.IO.Path]::GetTempFileName()
    try {
        Set-Content -Path $tempFile -Value $body -Encoding UTF8
        
        $args = @('issue', 'create', '--repo', $repo, '--title', $title, '--body-file', $tempFile)
        
        foreach ($label in $labels) {
            $args += @('--label', $label)
        }
        
        foreach ($assignee in $assignees) {
            $args += @('--assignee', $assignee)
        }
        
        $result = gh @args 2>&1
        Write-Host "  $result" -ForegroundColor Green
        
        # Extract issue number from result (format: https://github.com/owner/repo/issues/123)
        if ($result -match "/issues/(\d+)") {
            $issueNumber = [int]$matches[1]
            $createdIssueNumbers += $issueNumber
            Write-Host "  Issue #$issueNumber criada" -ForegroundColor Green
        }
    }
    finally {
        Remove-Item $tempFile -ErrorAction SilentlyContinue
    }
}

if ($DryRun) {
    Write-Host "`n[dry-run] Terminado. Nenhuma issue foi criada." -ForegroundColor Yellow
    exit 0
}

if ($createdIssueNumbers.Count -eq 0) {
    Write-Host "`nNenhuma issue foi criada." -ForegroundColor Yellow
    exit 0
}

Write-Host "`nAdicionando issues ao Project #$ProjectNumber (owner: $Owner)..." -ForegroundColor Cyan

foreach ($issueNum in $createdIssueNumbers) {
    $issueUrl = "https://github.com/$repo/issues/$issueNum"
    Write-Host "  Adicionando issue #$issueNum ao project..." -ForegroundColor Cyan
    
    try {
        $addResult = gh project item-add $ProjectNumber --owner $Owner --url $issueUrl 2>&1
        Write-Host "    $addResult" -ForegroundColor Green
    }
    catch {
        Write-Host "    Erro ao adicionar issue #$issueNum ao project: $_" -ForegroundColor Red
    }
}

Write-Host "`n✅ Concluído! Issues criadas e adicionadas ao Project." -ForegroundColor Green
Write-Host "Visualize o project em: https://github.com/users/$Owner/projects/$ProjectNumber" -ForegroundColor Cyan
